### ISSUE TITLE
Odd error as soon as I start winfstest

### ISSUE THREAD

**Issue by andysyncplicity** [dimov-cz/winfstest#1]
I'm trying to check out winfstest, but as soon as I start it, I get an odd error:

```
C:\Users\GWBasic\Desktop\winfstest-master\TestSuite>run-winfstest.bat "C:\Users\GWBasic\Desktop\New folder\A"
C:\Users\GWBasic\Desktop\winfstest-master\TestSuite\t\base\00.t
Command '['C:\\Python27\\python.exe', 'C:\\Users\\GWBasic\\Desktop\\winfstest-master\\TestSuite\\t\\base\\00.t', 'C:\\Users\\GWBasic\\Desktop\\New folder\\A']' returned non-zero exit status 1
usage: CreateFile FileName DesiredAccess ShareMode 0 CreationDisposition FlagsAndAttributes 0
Traceback (most recent call last):
  File "C:\Users\GWBasic\Desktop\winfstest-master\TestSuite\t\base\00.t", line 10, in <module>
    expect("CreateFile %s GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % name, 0)
  File "C:\Users\GWBasic\Desktop\winfstest-master\TestSuite\winfstest.py", line 136, in expect
    pass
  File "C:\Users\GWBasic\Desktop\winfstest-master\TestSuite\winfstest.py", line 91, in __exit__
    raise subprocess.CalledProcessError(ret, self.cmd)
subprocess.CalledProcessError: Command 'CreateFile C:\Users\GWBasic\Desktop\New folder\A\50061bda GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0' returned non-zero exit status 1
```

Unfortunately, I really don't know how to diagnose this. Any ideas?

**Comment by dimov-cz** [comment]
Not sure, maybe arguments, current version use:
run-winfstest.bat <folder-with-tests> "C:\Users\GWBasic\Desktop\New folder\A"
